language: java
sudo: true

jdk:
  - oraclejdk8

script:
  - ./gradlew -v
  - ./gradlew clean test

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in SecretKey.gpg.enc -out GPGKey.gpg -d